-- MySQL Script generated by MySQL Workbench
-- pon, 8 sty 2018, 22:21:48
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `idusers` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(60) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idusers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`trening`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`trening` (
  `idtrening` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nazwa_treningu` VARCHAR(70) NULL DEFAULT NULL,
  `users_idusers` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idtrening`, `users_idusers`),
  INDEX `fk_trening_users1_idx` (`users_idusers` ASC),
  CONSTRAINT `fk_trening_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `mydb`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cwiczenie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cwiczenie` (
  `idcwiczenie` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nazwa_cwiczenia` VARCHAR(45) NULL DEFAULT NULL,
  `powtorzenia` INT UNSIGNED NULL DEFAULT NULL,
  `serie` INT UNSIGNED NULL DEFAULT NULL,
  `przerwa` INT UNSIGNED NULL DEFAULT NULL,
  `trening_idtrening` INT UNSIGNED NOT NULL,
  `trening_users_idusers` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idcwiczenie`, `trening_idtrening`, `trening_users_idusers`),
  INDEX `fk_cwiczenie_trening1_idx` (`trening_idtrening` ASC, `trening_users_idusers` ASC),
  CONSTRAINT `fk_cwiczenie_trening1`
    FOREIGN KEY (`trening_idtrening` , `trening_users_idusers`)
    REFERENCES `mydb`.`trening` (`idtrening` , `users_idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`wymiary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`wymiary` (
  `idwymiary` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `wzrost` FLOAT UNSIGNED NULL DEFAULT NULL,
  `waga` FLOAT UNSIGNED NULL DEFAULT NULL,
  `ramie` FLOAT UNSIGNED NULL DEFAULT NULL,
  `udo` FLOAT UNSIGNED NULL DEFAULT NULL,
  `pas` FLOAT UNSIGNED NULL DEFAULT NULL,
  `nadgarstek` FLOAT UNSIGNED NULL DEFAULT NULL,
  `kostka` FLOAT UNSIGNED NULL DEFAULT NULL,
  `przedramie` FLOAT UNSIGNED NULL DEFAULT NULL,
  `lydka` FLOAT UNSIGNED NULL DEFAULT NULL,
  `data` DATE NULL DEFAULT NULL,
  `users_idusers` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idwymiary`, `users_idusers`),
  INDEX `fk_wymiary_users_idx` (`users_idusers` ASC),
  CONSTRAINT `fk_wymiary_users`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `mydb`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`zapotrzebowanie_kaloryczne`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`zapotrzebowanie_kaloryczne` (
  `idzapotrzebowanie_kaloryczne` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `chudniecie` INT UNSIGNED NULL DEFAULT NULL,
  `utrzymanie` INT UNSIGNED NULL DEFAULT NULL,
  `tycie` INT UNSIGNED NULL DEFAULT NULL,
  `users_idusers` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idzapotrzebowanie_kaloryczne`, `users_idusers`),
  INDEX `fk_zapotrzebowanie_kaloryczne_users1_idx` (`users_idusers` ASC),
  CONSTRAINT `fk_zapotrzebowanie_kaloryczne_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `mydb`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`posilek`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`posilek` (
  `idposilek` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `kalorie` FLOAT UNSIGNED NULL DEFAULT NULL,
  `bialko` FLOAT UNSIGNED NULL DEFAULT NULL,
  `weglowodany` FLOAT UNSIGNED NULL DEFAULT NULL,
  `tluszcze` FLOAT UNSIGNED NULL DEFAULT NULL,
  `nazwa` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idposilek`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
